name = "katanakit-js"
main = "src/worker.js"
compatibility_date = "2026-09-09"

route = { pattern = "senseikatana.com/packages/katanakit-js/*", zone_name = "senseikatana.com" }

[assets]
directory = "./dist/katanakit-js"
binding = "ASSETS"
