name = "katanakit-js"
main = "src/index.js"
compatibility_date = "2026-09-09"

route = { pattern = "senseikatana.com/katanakit-js/*", zone_name = "senseikatana.com" }

[assets]
directory = "./docs/build"
