name = "katanakit-js"
main = "src/worker.js"
compatibility_date = "2026-09-09"
workers_dev = true

routes = [
	{ pattern = "senseikatana.com/*", zone_name = "senseikatana.com" },
]

[assets]
directory = "./dist/katanakit-js"
binding = "ASSETS"
